import "server-only";
import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import type {GenerationMode,GenerationStatus,WorkflowType} from "./ai/types";
import type {ApiProviderType,ModelSlot} from "./ai/provider-settings-types";

export type ProductType="上衣"|"裤装"|"连衣裙"|"半身裙"|"套装";
export type StepStatus="not_started"|"ready"|"generating"|"partial_success"|"awaiting_confirmation"|"confirmed"|"failed"|"stale"|"completed";
export type DependencyStatus="current"|"stale"|"needs_review";
export type ProjectAssets={garmentImage?:string;productDetailImage?:string;brandTagImage?:string;modelReferenceImage?:string;fabricTextureImage?:string;otherMaterialImages?:string[];modelImage?:string;standalonePoseInputImage?:string;colorReferenceImage?:string;standaloneRecolorPoseImages?:string[]};
export type ProductAttributes={mainColor?:string;printType?:string;neckline?:string;sleeveType?:string;garmentLength?:string;fit?:string;fabric?:string;transparency?:string;lining?:string;elasticity?:string};
export type ProductProfile={brand?:string;season?:string;listingDate?:string;owner?:string;reviewStatus?:"draft"|"awaiting_review"|"confirmed";notes?:string;detailDescription?:string;tags?:string[];attributes?:ProductAttributes};
export type TargetColor={id:string;name:string;hex?:string;cropImage?:string;cropRegion?:{x:number;y:number;width:number;height:number};status:"draft"|"ready"|"generating"|"partial_success"|"success"|"failed"|"confirmed"|"stale";poseResults?:string[];protectedAreas?:string[]};
export type WorkflowSettings={tryon?:{mode:GenerationMode;candidateCount:number;productType?:ProductType;garmentDescription:string;detailRequirements:string;protectedItems:string[]};pose?:{mode:GenerationMode;productType?:ProductType;shotType:string;face:boolean;background:boolean;detailRequirements:string;poseInstructions:string[];sourceMode:"confirmed"|"standalone"};recolor?:{mode:GenerationMode;garmentArea:string;protectedAreas:string[];extraRequirements:string;activeColorId?:string;sourceMode:"confirmed"|"standalone"};[key:string]:unknown};
export type Project={id:string;sku:string;productName:string;productType:ProductType;currentStep:number;status:string;createdAt:string;updatedAt:string;confirmedTryonImage?:string;confirmedPoseImages?:string[];confirmedRecolorImages?:string[];assets:ProjectAssets;profile?:ProductProfile;settings:WorkflowSettings;stepStatuses?:Record<string,StepStatus>;dependencyStatus?:DependencyStatus;targetColors?:TargetColor[]};
export type JobPhase="queued"|"uploading"|"submitting"|"waiting_provider"|"downloading"|"validating"|"saving"|"success"|"failed"|"interrupted";
export type Job={id:string;projectId:string;sku:string;workflow:WorkflowType;provider:string;providerId?:string;providerType?:ApiProviderType|string;model:string;modelSlot?:ModelSlot;mode:GenerationMode;inputImages:string[];outputImages:string[];promptVersion:string;status:GenerationStatus;requestStatus?:GenerationStatus;phase?:JobPhase;dependencyStatus?:DependencyStatus;startedAt:string;requestStartedAt?:string;finishedAt?:string;requestFinishedAt?:string;error?:string;errorMessage?:string;slot?:number;poseIndex?:number;poseInstruction?:string;targetColorId?:string;colorName?:string};
export type OperationStatus="queued"|"running"|"success"|"failed"|"interrupted";
export type Operation={id:string;projectId:string;workflow:WorkflowType;status:OperationStatus;payload:unknown;jobIds:string[];createdAt:string;updatedAt:string;error?:string};
type Store={projects:Project[];jobs:Job[];operations:Operation[]};

const dataDir=path.join(process.cwd(),"data"),file=path.join(dataDir,"store.json"),backup=path.join(dataDir,"store.backup.json");let queue=Promise.resolve();
const defaults=():Store=>({projects:[],jobs:[],operations:[]});
async function load():Promise<Store>{try{const parsed=JSON.parse(await fs.readFile(file,"utf8")) as Store;parsed.projects??=[];parsed.jobs??=[];parsed.operations??=[];return parsed}catch(error){try{const parsed=JSON.parse(await fs.readFile(backup,"utf8")) as Store;parsed.projects??=[];parsed.jobs??=[];parsed.operations??=[];return parsed}catch{if((error as NodeJS.ErrnoException).code!=="ENOENT")console.error("项目数据损坏，且备份不可用");return defaults()}}}
async function mutate<T>(fn:(s:Store)=>T|Promise<T>){let result!:T;queue=queue.then(async()=>{const s=await load();result=await fn(s);await fs.mkdir(dataDir,{recursive:true});try{await fs.copyFile(file,backup)}catch{}const tmp=file+".tmp";await fs.writeFile(tmp,JSON.stringify(s,null,2));await fs.rename(tmp,file)});await queue;return result}
const normalize=(p:Project):Project=>({...p,assets:p.assets||{},profile:p.profile||{reviewStatus:"draft",tags:[],attributes:{}},settings:p.settings||{},stepStatuses:p.stepStatuses||{"1":"ready","2":"not_started","3":"not_started","4":"not_started","5":"not_started"},dependencyStatus:p.dependencyStatus||"current",targetColors:p.targetColors||[]});
export const listProjects=async()=>{const s=await load();return s.projects.map(normalize).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))};
export const getProject=async(id:string)=>{const p=(await load()).projects.find(x=>x.id===id);return p?normalize(p):undefined};
export const createProject=(v:Pick<Project,"sku"|"productName"|"productType">)=>mutate(s=>{if(s.projects.some(x=>x.sku===v.sku))throw new Error("SKU 已存在");const now=new Date().toISOString();const p:Project={...v,id:crypto.randomUUID(),currentStep:1,status:"未开始",createdAt:now,updatedAt:now,assets:{},settings:{},stepStatuses:{"1":"ready","2":"not_started","3":"not_started","4":"not_started","5":"not_started"},dependencyStatus:"current",targetColors:[]};s.projects.push(p);return p});
export const updateProject=(id:string,patch:Partial<Project>)=>mutate(s=>{const p=s.projects.find(x=>x.id===id);if(!p)throw new Error("商品项目不存在");Object.assign(p,patch,{id:p.id,updatedAt:new Date().toISOString()});return normalize(p)});
export const deleteProject=(id:string)=>mutate(s=>{s.projects=s.projects.filter(x=>x.id!==id);s.jobs=s.jobs.filter(x=>x.projectId!==id);s.operations=s.operations.filter(x=>x.projectId!==id)});
export const listJobs=async(filters?:{sku?:string;workflow?:string;projectId?:string})=>{let j=(await load()).jobs;if(filters?.sku)j=j.filter(x=>x.sku.includes(filters.sku!));if(filters?.workflow)j=j.filter(x=>x.workflow===filters.workflow);if(filters?.projectId)j=j.filter(x=>x.projectId===filters.projectId);return j.sort((a,b)=>b.startedAt.localeCompare(a.startedAt))};
export const addJob=(job:Job)=>mutate(s=>{s.jobs.push(job);return job});
export const patchJob=(id:string,patch:Partial<Job>)=>mutate(s=>{const j=s.jobs.find(x=>x.id===id);if(!j)throw new Error("任务不存在");Object.assign(j,patch,{id:j.id});return j});
export const getJob=async(id:string)=>(await load()).jobs.find(x=>x.id===id);
export const deleteWorkflowRecords=(projectId:string,workflow:WorkflowType)=>mutate(s=>{const jobIds=new Set(s.jobs.filter(job=>job.projectId===projectId&&job.workflow===workflow).map(job=>job.id));s.jobs=s.jobs.filter(job=>!jobIds.has(job.id));s.operations=s.operations.filter(operation=>!(operation.projectId===projectId&&operation.workflow===workflow));return jobIds.size});
export const markInterruptedJobs=()=>mutate(s=>{for(const j of s.jobs)if(j.phase&&!["success","failed","interrupted"].includes(j.phase)){j.phase="interrupted";j.status="failed";j.error="服务重启导致任务中断，请重新生成";j.finishedAt=new Date().toISOString()}return true});
export const addOperation=(operation:Operation)=>mutate(s=>{s.operations.push(operation);return operation});
export const getOperation=async(id:string)=>(await load()).operations.find(x=>x.id===id);
export const patchOperation=(id:string,patch:Partial<Operation>)=>mutate(s=>{const operation=s.operations.find(x=>x.id===id);if(!operation)throw new Error("本地任务不存在");Object.assign(operation,patch,{id:operation.id,updatedAt:new Date().toISOString()});return operation});
export const listOperations=async(projectId?:string)=>{const operations=(await load()).operations;return (projectId?operations.filter(x=>x.projectId===projectId):operations).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))};
export const markInterruptedOperations=()=>mutate(s=>{for(const operation of s.operations)if(operation.status==="queued"||operation.status==="running"){operation.status="interrupted";operation.error="服务重启导致任务中断，请重新生成";operation.updatedAt=new Date().toISOString()}return true});
export const reconcileGeneratingProjects=()=>mutate(s=>{const now=new Date().toISOString();for(const project of s.projects){const active=s.operations.some(operation=>operation.projectId===project.id&&(operation.status==="queued"||operation.status==="running"));if(active)continue;const statuses=project.stepStatuses||{};if(project.status==="生成中"||Object.values(statuses).includes("generating")){project.status="生成失败";project.stepStatuses=Object.fromEntries(Object.entries(statuses).map(([step,status])=>[step,status==="generating"?"failed":status]));project.targetColors=(project.targetColors||[]).map(color=>color.status==="generating"?{...color,status:"failed"}:color);project.updatedAt=now}}return true});
