import "server-only";
import crypto from "node:crypto";
import sharp from "sharp";
import {addJob,getProject,listJobs,patchJob,updateProject,type ProductType,type Project,type TargetColor} from "./db";
import {generateImage} from "./ai/generate";
import {resolveWorkflowModel} from "./ai/provider-settings";
import {downloadImage,localImage,saveOutput,toDataUrl} from "./ai/storage";
import {sha,validateOutput,validateUpload,safeSegment} from "./ai/validators";
import type {GenerationMode,WorkflowType} from "./ai/types";
import type {ModelSlot} from "./ai/provider-settings-types";
import {tryonPrompt,TRYON_PROMPT_VERSION} from "./ai/prompts/tryon";
import {posePrompt,POSE_PROMPT_VERSION} from "./ai/prompts/pose";
import {recolorPrompt,RECOLOR_PROMPT_VERSION} from "./ai/prompts/recolor";
import {POSE_PRESETS} from "./ai/pose-presets";

export const DEFAULT_DETAILS="保持服装领口、袖口、肩部、下摆、纽扣数量、印花位置、白色包边、面料纹理和服装长度，不得增加或删除口袋、腰带、纽扣、印花或装饰。";
export async function persistUpload(file:File,sku:string,name:string){const data=await validateUpload(file);const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";return saveOutput(sku,"source",`${safeSegment(name)}-${crypto.randomUUID()}.${ext}`,data)}
const mimeFrom=(u:string)=>u.endsWith(".png")?"image/png":u.endsWith(".webp")?"image/webp":"image/jpeg";
async function existingHashes(projectId:string,workflow:WorkflowType,excludeSlot:number){const jobs=await listJobs({projectId,workflow});const urls=jobs.filter(j=>j.slot!==excludeSlot).flatMap(j=>j.outputImages);const hashes=[];for(const u of urls)try{hashes.push(sha(await localImage(u)))}catch{}return hashes}
async function latestSlotJobs(projectId:string,workflow:WorkflowType,targetColorId?:string){
  const latest=new Map<number,(Awaited<ReturnType<typeof listJobs>>)[number]>();
  for(const job of await listJobs({projectId,workflow})){
    if(targetColorId!==undefined&&job.targetColorId!==targetColorId)continue;
    const slot=job.slot||0;if(slot&&!latest.has(slot))latest.set(slot,job);
  }
  return latest;
}
function slotState(latest:Map<number,{status:string}>,expected:number){
  const values=Array.from({length:expected},(_,index)=>latest.get(index+1));
  const success=values.filter(job=>job&&["success","needs_review","confirmed"].includes(job.status)).length;
  return success===0?"failed":success<expected?"partial_success":"awaiting_confirmation";
}
async function markJobsStale(projectId:string,workflows:WorkflowType[]){for(const j of await listJobs({projectId}))if(workflows.includes(j.workflow)&&!["failed","stale"].includes(j.status))await patchJob(j.id,{status:"stale",dependencyStatus:"stale"})}
async function invalidate(p:Project,from:"tryon"|"pose"|"color"){
  const staleColors=(p.targetColors||[]).map(color=>color.poseResults?.length?{...color,status:"stale" as const}:color);
  if(from==="tryon"){
    await markJobsStale(p.id,["pose","recolor"]);
    await updateProject(p.id,{status:"需要重新审核",dependencyStatus:"needs_review",targetColors:staleColors,stepStatuses:{...p.stepStatuses,"3":"stale","4":"stale","5":"stale"}});
  }else if(from==="pose"){
    await markJobsStale(p.id,["recolor"]);
    await updateProject(p.id,{status:"需要重新审核",dependencyStatus:"needs_review",targetColors:staleColors,stepStatuses:{...p.stepStatuses,"4":"stale","5":"stale"}});
  }else await updateProject(p.id,{targetColors:(p.targetColors||[]).map(color=>({...color,status:color.status==="draft"?"draft":"stale"})),dependencyStatus:"needs_review",stepStatuses:{...p.stepStatuses,"4":"stale","5":"stale"},status:"需要重新审核"});
}

async function runOne(args:{projectId:string;workflow:WorkflowType;mode:GenerationMode;modelSlot?:ModelSlot;images:string[];prompt:string;promptVersion:string;folder:string;filename:string;slot:number;otherHashes?:string[];poseInstruction?:string;targetColorId?:string;colorName?:string}){
  const project=await getProject(args.projectId);if(!project)throw new Error("项目不存在");const choice=await resolveWorkflowModel(args.workflow,args.mode,args.modelSlot||"primary"),id=crypto.randomUUID(),seed=crypto.randomInt(0,2**32),startedAt=new Date().toISOString();
  await addJob({id,projectId:project.id,sku:project.sku,workflow:args.workflow,provider:choice.name,providerId:choice.id,providerType:choice.type,model:choice.model,modelSlot:args.modelSlot||"primary",mode:args.mode,inputImages:args.images,outputImages:[],promptVersion:args.promptVersion,status:"queued",requestStatus:"queued",phase:"queued",dependencyStatus:"current",startedAt,requestStartedAt:startedAt,slot:args.slot,poseIndex:args.workflow==="pose"?args.slot:undefined,poseInstruction:args.poseInstruction,targetColorId:args.targetColorId,colorName:args.colorName});
  try{await patchJob(id,{status:"generating",requestStatus:"generating",phase:"uploading"});const sourceBuffers=await Promise.all(args.images.map(localImage)),dataUrls=sourceBuffers.map((buffer,index)=>toDataUrl(buffer,mimeFrom(args.images[index]))),inputHashes=sourceBuffers.map(sha);await patchJob(id,{phase:"submitting"});await patchJob(id,{phase:"waiting_provider"});const generated=await generateImage({workflow:args.workflow,provider:choice.type,model:choice.model,images:dataUrls,prompt:args.prompt,options:{mode:args.mode,sku:project.sku,candidate:args.slot,seed}},choice);await patchJob(id,{phase:"downloading"});const downloaded=generated.imageBase64?{buffer:Buffer.from(generated.imageBase64,"base64"),mime:generated.mimeType||"image/jpeg"}:await downloadImage(generated.temporaryImageUrl!);await patchJob(id,{phase:"validating"});const checks=await validateOutput(downloaded.buffer,downloaded.mime,inputHashes,args.otherHashes,args.workflow==="recolor"?sourceBuffers[0]:undefined);await patchJob(id,{phase:"saving"});const jpeg=await sharp(downloaded.buffer).jpeg({quality:94}).toBuffer(),url=await saveOutput(project.sku,args.folder,args.filename,jpeg),review=checks.needsReview,finishedAt=new Date().toISOString();await patchJob(id,{status:review?"needs_review":"success",requestStatus:review?"needs_review":"success",phase:"success",outputImages:[url],finishedAt,requestFinishedAt:finishedAt});return {id,url,provider:choice.name,providerId:choice.id,providerType:choice.type,model:choice.model,hash:sha(jpeg),status:review?"needs_review":"success",warnings:checks.warnings}}
  catch(e){const error=e instanceof Error?e.message:"未知生成错误",finishedAt=new Date().toISOString();await patchJob(id,{status:"failed",requestStatus:"failed",phase:"failed",error,errorMessage:error,finishedAt,requestFinishedAt:finishedAt});return {id,error,provider:choice.name,providerId:choice.id,providerType:choice.type,model:choice.model,status:"failed"}}
}

export async function executeTryon(v:{projectId:string;productType:ProductType;garmentImage:string;modelImage:string;garmentDescription:string;detailRequirements:string;mode:GenerationMode;candidateCount:number;slot?:number;modelPreference?:ModelSlot}){const p=await getProject(v.projectId);if(!p)throw new Error("项目不存在");await resolveWorkflowModel("tryon",v.mode,v.modelPreference||"primary");await invalidate(p,"tryon");await updateProject(p.id,{productType:v.productType,status:"生成中",assets:{...p.assets,garmentImage:v.garmentImage,modelReferenceImage:v.modelImage,modelImage:v.modelImage},settings:{...p.settings,tryon:{mode:v.mode,candidateCount:v.candidateCount,productType:v.productType,garmentDescription:v.garmentDescription,detailRequirements:v.detailRequirements,protectedItems:p.settings.tryon?.protectedItems||[]}},stepStatuses:{...p.stepStatuses,"2":"generating"}});const slots=v.slot?[v.slot]:Array.from({length:v.candidateCount},(_,i)=>i+1),results=[],hashes:string[]=v.slot?await existingHashes(p.id,"tryon",v.slot):[];for(const slot of slots){const r=await runOne({projectId:p.id,workflow:"tryon",mode:v.mode,modelSlot:v.modelPreference,images:[v.modelImage,v.garmentImage],prompt:tryonPrompt(v.productType,v.garmentDescription,v.detailRequirements),promptVersion:TRYON_PROMPT_VERSION,folder:"tryon",filename:`${safeSegment(p.sku)}_tryon_${String(slot).padStart(2,"0")}.jpg`,slot,otherHashes:hashes});if("hash" in r)hashes.push(r.hash!);results.push(r)}const expected=v.slot?(p.settings.tryon?.candidateCount||v.candidateCount):v.candidateCount,status=slotState(await latestSlotJobs(p.id,"tryon"),expected);await updateProject(p.id,{status:status==="failed"?"生成失败":"等待人工确认",stepStatuses:{...p.stepStatuses,"2":status}});return results}

export async function executePose(v:{projectId:string;sourceImage:string;mode:GenerationMode;shotType:string;face:boolean;background:boolean;detailRequirements:string;poseInstructions?:string[];slot?:number;modelPreference?:ModelSlot}){const p=await getProject(v.projectId);if(!p)throw new Error("项目不存在");await resolveWorkflowModel("pose",v.mode,v.modelPreference||"primary");await invalidate(p,"pose");const instructions=v.poseInstructions?.length===3?v.poseInstructions:POSE_PRESETS[p.productType],slots=v.slot?[v.slot]:[1,2,3],results=[],hashes:string[]=v.slot?await existingHashes(p.id,"pose",v.slot):[];await updateProject(p.id,{status:"生成中",settings:{...p.settings,pose:{mode:v.mode,productType:p.productType,shotType:v.shotType,face:v.face,background:v.background,detailRequirements:v.detailRequirements,poseInstructions:instructions,sourceMode:p.assets.standalonePoseInputImage===v.sourceImage?"standalone":"confirmed"}},stepStatuses:{...p.stepStatuses,"3":"generating"}});for(const slot of slots){const instruction=instructions[slot-1];
const r=await runOne({projectId:p.id,workflow:"pose",mode:v.mode,modelSlot:v.modelPreference,images:[v.sourceImage],prompt:posePrompt(instruction,p.productType,v.shotType,v.face,v.background,v.detailRequirements),promptVersion:POSE_PROMPT_VERSION,folder:"pose",filename:`${safeSegment(p.sku)}_original_pose${String(slot).padStart(2,"0")}.jpg`,slot,otherHashes:hashes,poseInstruction:instruction});if("hash" in r)hashes.push(r.hash!);results.push(r)}const status=slotState(await latestSlotJobs(p.id,"pose"),3);await updateProject(p.id,{status:status==="failed"?"生成失败":"等待人工确认",stepStatuses:{...p.stepStatuses,"3":status}});return results}

export async function executeRecolor(v:{projectId:string;colorReferenceImage:string;colorReferenceCrop?:string;colorName:string;targetColorId?:string;hexColor:string;garmentArea:string;protectedAreas:string[];extraRequirements:string;mode:GenerationMode;poseImages?:string[];slot?:number;modelPreference?:ModelSlot}){const p=await getProject(v.projectId);if(!p)throw new Error("项目不存在");await resolveWorkflowModel("recolor",v.mode,v.modelPreference||"primary");const sources=v.poseImages?.length===3?v.poseImages:p.confirmedPoseImages;if(!sources?.length)throw new Error("请先确认三张姿势图或独立上传三张姿势图");const targetId=v.targetColorId||crypto.randomUUID(),slots=v.slot?[v.slot]:[1,2,3],results=[],hashes:string[]=v.slot?await existingHashes(p.id,"recolor",v.slot):[];const colors=[...(p.targetColors||[])],colorIndex=colors.findIndex(c=>c.id===targetId),color:TargetColor={id:targetId,name:v.colorName,hex:v.hexColor||undefined,cropImage:v.colorReferenceCrop,status:"generating",protectedAreas:v.protectedAreas};if(colorIndex>=0)colors[colorIndex]={...colors[colorIndex],...color};else colors.push(color);await updateProject(p.id,{status:"生成中",targetColors:colors,settings:{...p.settings,recolor:{mode:v.mode,garmentArea:v.garmentArea,protectedAreas:v.protectedAreas,extraRequirements:v.extraRequirements,activeColorId:targetId,sourceMode:v.poseImages?.length===3?"standalone":"confirmed"}},stepStatuses:{...p.stepStatuses,"4":"generating"}});for(const slot of slots){const source=sources[slot-1];if(!source){results.push({slot,status:"failed",error:"对应姿势图不存在"});continue}
const colorSample=v.colorReferenceCrop||v.colorReferenceImage;
const refs=colorSample?[source,colorSample]:[source];
const r=await runOne({projectId:p.id,workflow:"recolor",mode:v.mode,modelSlot:v.modelPreference,images:refs,prompt:recolorPrompt(v.garmentArea,v.colorName,v.hexColor,v.protectedAreas,v.extraRequirements),promptVersion:RECOLOR_PROMPT_VERSION,folder:`recolor/${safeSegment(v.colorName)}`,filename:`${safeSegment(p.sku)}_${safeSegment(v.colorName)}_pose${String(slot).padStart(2,"0")}.jpg`,slot,otherHashes:hashes,targetColorId:targetId,colorName:v.colorName});if("hash" in r)hashes.push(r.hash!);results.push(r)}const latestBySlot=await latestSlotJobs(p.id,"recolor",targetId),urls=Array.from({length:3},(_,index)=>latestBySlot.get(index+1)?.outputImages[0]).filter((url):url is string=>Boolean(url)),stepState=slotState(latestBySlot,3),colorState=stepState==="awaiting_confirmation"?"success":stepState;const latest=await getProject(p.id),updated=(latest?.targetColors||[]).map(c=>c.id===targetId?{...c,status:colorState,poseResults:urls} as TargetColor:c);await updateProject(p.id,{status:colorState==="failed"?"生成失败":"等待人工确认",targetColors:updated,stepStatuses:{...p.stepStatuses,"4":stepState}});return results}

export const invalidateForAssetChange=async(projectId:string,key:string)=>{const p=await getProject(projectId);if(!p)return;const jobs=await listJobs({projectId});if(["garmentImage","modelReferenceImage"].includes(key)){if(p.confirmedTryonImage||jobs.some(j=>j.workflow==="pose"||j.workflow==="recolor"))await invalidate(p,"tryon");else await updateProject(p.id,{stepStatuses:{...p.stepStatuses,"2":"ready"}})}else if(key==="standalonePoseInputImage"){if(p.confirmedPoseImages||jobs.some(j=>j.workflow==="recolor"))await invalidate(p,"pose");else await updateProject(p.id,{stepStatuses:{...p.stepStatuses,"3":"ready"}})}else if(["colorReferenceImage","standaloneRecolorPoseImages"].includes(key)){if((p.targetColors||[]).some(c=>c.poseResults?.length))await invalidate(p,"color");else await updateProject(p.id,{stepStatuses:{...p.stepStatuses,"4":"ready"}})}};
