import type {Metadata} from "next";
import {notFound} from "next/navigation";
import Link from "next/link";
import {featuredProjects,getProject,workflowSteps} from "@/content/portfolio";
import PlaceholderArt from "@/components/portfolio/PlaceholderArt";
import SiteHeader from "@/components/portfolio/SiteHeader";
import SiteFooter from "@/components/portfolio/SiteFooter";
export function generateStaticParams(){return featuredProjects.map(project=>({slug:project.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const project=getProject(slug);return {title:project?.title||"Project"}}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const project=getProject(slug);if(!project)notFound();const index=featuredProjects.findIndex(item=>item.slug===slug);const next=featuredProjects[(index+1)%featuredProjects.length];return <div className="portfolio-site"><SiteHeader/><main className="project-page"><header className="project-hero site-container"><p>{String(index+1).padStart(2,"0")} / {project.category}</p><h1>{project.title}</h1><div><p>{project.description}</p><dl><div><dt>Role</dt><dd>{project.role}</dd></div><div><dt>Year</dt><dd>{project.year}</dd></div><div><dt>Tools</dt><dd>{project.tools.join(" / ")}</dd></div></dl></div></header><section className="project-cover site-container"><PlaceholderArt label={project.placeholderLabel} index={index+1}/></section><section className="project-narrative site-container"><div><p>Overview</p><h2>{project.summary}</h2></div><ul>{project.highlights.map(item=><li key={item}>{item}</li>)}</ul></section>{slug==="modelflow"?<section className="case-workflow site-container"><p>Workflow / 11 steps</p><ol>{workflowSteps.map((step,stepIndex)=><li key={step}><span>{String(stepIndex+1).padStart(2,"0")}</span><strong>{step}</strong><small>对应过程素材待补充</small></li>)}</ol></section>:<section className="project-gallery site-container"><PlaceholderArt label="项目过程图待补充" index={index+1} tall/><PlaceholderArt label="项目细节图待补充" index={index+1}/><PlaceholderArt label="最终应用图待补充" index={index+1}/></section>}<section className="failure-note site-container"><p>Failure &amp; iteration</p><h2>失败不是被隐藏的结果，<br/>而是工作流继续进化的输入。</h2><p>此区域将展示失败样本、真实原因、判断标准与修复后的结果。目前仅保留结构，不使用虚假案例。</p></section><Link className="next-project site-container" href={`/work/${next.slug}`}><span>Next project</span><strong>{next.shortTitle}</strong><i>↗</i></Link></main><SiteFooter/></div>}
