import test from "node:test";
import assert from "node:assert/strict";
import {hasClearableSourceAssets,prepareSourceAssetCleanup} from "../src/lib/asset-cleanup";
import type {Project} from "../src/lib/db";

const project:Project={id:"project-1",sku:"SKU-1",productName:"测试商品",productType:"上衣",currentStep:4,status:"等待人工确认",createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",confirmedTryonImage:"/api/files/SKU-1/tryon/result.jpg",confirmedPoseImages:["/api/files/SKU-1/pose/1.jpg","/api/files/SKU-1/pose/2.jpg","/api/files/SKU-1/pose/3.jpg"],confirmedRecolorImages:["/api/files/SKU-1/recolor/red/1.jpg"],assets:{garmentImage:"/api/files/SKU-1/source/garment.jpg",modelReferenceImage:"/api/files/SKU-1/source/model.jpg",modelImage:"/api/files/SKU-1/source/model.jpg",colorReferenceImage:"/api/files/SKU-1/source/color.jpg",standalonePoseInputImage:"/api/files/SKU-1/source/pose.jpg",standaloneRecolorPoseImages:["/api/files/SKU-1/source/r1.jpg","/api/files/SKU-1/source/r2.jpg","/api/files/SKU-1/source/r3.jpg"]},settings:{},targetColors:[{id:"red",name:"红色",cropImage:"/api/files/SKU-1/source/colors/red.jpg",status:"confirmed",poseResults:["/api/files/SKU-1/recolor/red/1.jpg"]}]};

test("清空素材只移除源素材并保留所有生成和确认结果",()=>{const result=prepareSourceAssetCleanup(project);assert.deepEqual(result.assets,{});assert.equal(result.urls.length,8);assert.equal(result.targetColors[0].cropImage,undefined);assert.deepEqual(result.targetColors[0].poseResults,project.targetColors?.[0].poseResults);assert.equal(result.targetColors[0].status,"confirmed");assert.equal(project.confirmedTryonImage,"/api/files/SKU-1/tryon/result.jpg");assert.equal(project.confirmedPoseImages?.length,3);assert.equal(project.confirmedRecolorImages?.length,1)});
test("清空范围会去重同一模特素材且空素材时按钮不可用",()=>{const result=prepareSourceAssetCleanup(project);assert.equal(result.urls.filter(url=>url.endsWith("model.jpg")).length,1);assert.equal(hasClearableSourceAssets(project),true);assert.equal(hasClearableSourceAssets({...project,assets:{},targetColors:[]}),false)});
test("清空项目素材不会删除独立姿势库图片",()=>{const libraryImages=["/api/files/pose-library/assets/one.jpg","/api/files/pose-library/assets/two.jpg","/api/files/pose-library/assets/three.jpg"],withLibrary={...project,assets:{...project.assets,poseReferenceImages:libraryImages}};const result=prepareSourceAssetCleanup(withLibrary);assert.equal(result.urls.some(url=>url.startsWith("/api/files/pose-library/")),false);assert.deepEqual(withLibrary.assets.poseReferenceImages,libraryImages)});
