"use client";

import {useEffect,useRef,useState,type ClipboardEvent} from "react";

export type LocalAsset={file?:File;url?:string;name?:string;size?:number;width?:number;height?:number;status?:"idle"|"uploading"|"saved"|"failed";error?:string};

export default function AssetUploadCard({label,description,value,onChange,onPreview,onDelete}:{label:string;description?:string;value:LocalAsset;onChange:(asset:LocalAsset)=>void;onPreview:()=>void;onDelete?:()=>void}){
  const [drag,setDrag]=useState(false),[pasteError,setPasteError]=useState(""),input=useRef<HTMLInputElement>(null),card=useRef<HTMLDivElement>(null),objectUrl=useRef<string|undefined>(undefined),selection=useRef(0);
  function revokePreview(){if(objectUrl.current){URL.revokeObjectURL(objectUrl.current);objectUrl.current=undefined}}
  useEffect(()=>{if(objectUrl.current&&value.url!==objectUrl.current)revokePreview()},[value.url]);
  useEffect(()=>()=>{selection.current+=1;revokePreview()},[]);
  function accept(file?:File){if(!file)return;setPasteError("");selection.current+=1;const token=selection.current;revokePreview();const url=URL.createObjectURL(file);objectUrl.current=url;const image=new Image();image.onload=()=>{if(token!==selection.current)return;onChange({file,url,name:file.name,size:file.size,width:image.width,height:image.height,status:"idle"})};image.onerror=()=>{if(token!==selection.current)return;revokePreview();onChange({file,name:file.name,size:file.size,status:"idle"})};image.src=url}
  function pastedFile(items:DataTransferItemList,files:FileList){for(const item of Array.from(items)){if(item.kind==="file"&&item.type.startsWith("image/")){const file=item.getAsFile();if(file)return file}}return Array.from(files).find(file=>file.type.startsWith("image/"))}
  function handlePaste(event:ClipboardEvent<HTMLDivElement>){const file=pastedFile(event.clipboardData.items,event.clipboardData.files);if(!file){setPasteError("剪贴板中没有可用图片");return}event.preventDefault();accept(file)}
  async function pasteFromClipboard(){setPasteError("");try{if(!navigator.clipboard?.read)throw new Error("当前浏览器不允许按钮读取剪贴板，请点击卡片后按 Ctrl+V 或 Command+V");const items=await navigator.clipboard.read();for(const item of items){const type=item.types.find(value=>value.startsWith("image/"));if(!type)continue;const blob=await item.getType(type),extension=type.split("/")[1]?.replace("jpeg","jpg")||"png";accept(new File([blob],`clipboard-${Date.now()}.${extension}`,{type}));card.current?.focus();return}throw new Error("剪贴板中没有可用图片")}catch(error){setPasteError(error instanceof Error?error.message:"无法读取剪贴板图片")}}
  return <div><h3 style={{marginBottom:8}}>{label}</h3><div ref={card} className={`${drag?"upload-card drag":"upload-card"}${value.url?" has-image":""}`} onDragOver={event=>{event.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={event=>{event.preventDefault();setDrag(false);accept(event.dataTransfer.files[0])}} onPaste={handlePaste} tabIndex={0} aria-label={`${label}，可点击后粘贴图片`}>
    {value.url?<><button type="button" className="asset-preview-button" onClick={onPreview} aria-label={`查看${label}大图`}><img src={value.url} alt={label}/><span>查看大图</span></button><div className="upload-meta"><span>{value.name||"已保存图片"}<br/>{value.width?`${value.width}×${value.height} · `:""}{value.size?`${(value.size/1024/1024).toFixed(2)} MB`:"持久化素材"}<br/>{value.status==="uploading"?"正在上传":value.status==="failed"?value.error:"保存成功"}</span><span><button type="button" className="replace" onClick={event=>{event.preventDefault();input.current?.click()}}>更换</button>{onDelete&&<button type="button" className="replace" onClick={event=>{event.preventDefault();onDelete()}}>删除</button>}</span></div></>:<div className="upload-empty"><div><b>＋ 上传{label}</b><span>{description||"点击、拖拽或粘贴图片"}<br/>支持常见照片格式，最大 30MB</span></div></div>}
    <input ref={input} type="file" accept="image/*,.jpg,.jpeg,.jfif,.png,.webp,.avif,.heic,.heif,.gif,.tif,.tiff,.bmp" onChange={event=>{accept(event.target.files?.[0]);event.currentTarget.value=""}} aria-label={`上传${label}`}/>
  </div><div className="upload-paste-actions"><button type="button" className="text-button" onClick={()=>void pasteFromClipboard()}>⎘ 粘贴剪贴板图片</button><small>也可点击上方卡片后按 Ctrl+V / Command+V</small></div>{pasteError&&<div className="upload-paste-error" role="alert">{pasteError}</div>}</div>;
}
