"use client";

import {useState} from "react";
import type {PanelProps} from "./types";
import AssetUploadCard,{type LocalAsset} from "./AssetUploadCard";
import ResultCard from "./ResultCard";
import ImagePreviewDialog from "./ImagePreviewDialog";
import ClearAssetsButton from "./ClearAssetsButton";
import ClearResultsButton from "./ClearResultsButton";
import {POSE_PRESETS} from "@/lib/ai/pose-presets";
import {hasClearableSourceAssets} from "@/lib/asset-cleanup";
import {hasWorkflowResults} from "@/lib/result-cleanup";

const DETAILS="保持服装领口、袖口、肩部、下摆、纽扣、印花、面料纹理和服装长度，不得改变商品设计。";

export default function PosePanel({p,jobs,health,modelRouting,busy,run,persistAsset,deleteAsset,clearSourceAssets,clearWorkflowResults,saveProject,post,confirmFlow}:PanelProps){
  const saved=p.settings.pose,savedMatchesProduct=saved?.productType===p.productType;
  const preset=savedMatchesProduct&&saved?.poseInstructions?.length===3?saved.poseInstructions:POSE_PRESETS[p.productType];
  const [mode,setMode]=useState<"fast"|"standard"|"quality">(saved?.mode||"standard"),[shot,setShot]=useState(saved?.shotType||"全身"),[face,setFace]=useState(saved?.face||false),[background,setBackground]=useState(saved?.background??true),[details,setDetails]=useState(saved?.detailRequirements||DETAILS),[instructions,setInstructions]=useState(preset),[sourceMode,setSourceMode]=useState<"confirmed"|"standalone">(saved?.sourceMode||(p.confirmedTryonImage?"confirmed":"standalone")),[source,setSource]=useState<LocalAsset>({url:p.assets.standalonePoseInputImage,name:"独立姿势输入图",status:p.assets.standalonePoseInputImage?"saved":"idle"}),[selected,setSelected]=useState<string[]>(p.confirmedPoseImages||jobs.flatMap(j=>j.outputImages)),[preview,setPreview]=useState<{images:string[];index:number}|null>(null);
  const sourceUrl=sourceMode==="confirmed"?p.confirmedTryonImage:source.url,route=modelRouting.pose,routed=route.primary.source==="stored";
  const configured=routed?route.primary.configured:health.poseProvider==="volcengine"?health.volcengine:mode==="standard"?health.volcengine:mode==="fast"?health.fluxKlein:health.fluxPro;
  const images=jobs.flatMap(j=>j.outputImages),modelLabel=routed?route.primary.model:health.poseProvider==="volcengine"?"Seedream 5.0":"FLUX";
  async function persist(a:LocalAsset){setSource({...a,status:"uploading"});try{const url=await persistAsset(a.file,"standalonePoseInputImage","pose-source");setSource({...a,url,file:undefined,status:"saved"})}catch(e){setSource({...a,status:"failed",error:e instanceof Error?e.message:"上传失败"});throw e}}
  async function saveSettings(){await saveProject({settings:{...p.settings,pose:{mode,productType:p.productType,shotType:shot,face,background,detailRequirements:details,poseInstructions:instructions,sourceMode}}})}
  async function clearAllAssets(){await clearSourceAssets();setSource({status:"idle"});setPreview(null)}
  async function clearResults(){await clearWorkflowResults("pose");setSelected([]);setPreview(null)}
  async function start(slot?:number,modelPreference:"primary"|"fallback"="primary"){if(!sourceUrl)throw new Error("请选择已确认换装图或独立上传一张模特商品图");await saveSettings();await post("/api/pose",{projectId:p.id,sourceImage:sourceUrl,mode,shotType:shot,face,background,detailRequirements:details,poseInstructions:instructions,modelPreference,...(slot?{slot}:{})})}
  return <><div className="workbench-grid">
    <section className="card"><div className="panel-head"><h2>姿势输入来源</h2><div className="panel-actions"><span className="badge">两种方式</span><ClearAssetsButton disabled={busy||!hasClearableSourceAssets(p)} onConfirm={clearAllAssets}/></div></div><div className="segment"><button className={sourceMode==="confirmed"?"active":""} disabled={!p.confirmedTryonImage} onClick={()=>setSourceMode("confirmed")}>使用已确认换装图</button><button className={sourceMode==="standalone"?"active":""} onClick={()=>setSourceMode("standalone")}>独立上传图片</button></div>{sourceMode==="confirmed"&&p.confirmedTryonImage?<img className="result-image" src={p.confirmedTryonImage} alt="已确认换装图"/>:<AssetUploadCard label="模特商品图" description="不经过换装也可以直接上传" value={source} onChange={a=>run(()=>persist(a))} onDelete={()=>run(async()=>{await deleteAsset("standalonePoseInputImage");setSource({status:"idle"})})} onPreview={()=>source.url&&setPreview({images:[source.url],index:0})}/>}<label className="field">服装细节保护<textarea value={details} onChange={e=>setDetails(e.target.value)}/></label></section>
    <section className="card"><div className="panel-head"><h2>三种姿势结果</h2><div className="panel-actions"><span className="badge">3个独立子任务</span><ClearResultsButton workflow="pose" disabled={busy||!hasWorkflowResults(p,jobs,"pose")} onConfirm={clearResults}/></div></div><div className="result-grid three">{[1,2,3].map(slot=>{const job=jobs.find(item=>item.slot===slot),url=job?.outputImages[0];return <div key={slot}><ResultCard job={job} label={`姿势 ${String(slot).padStart(2,"0")}`} selected={!!url&&selected.includes(url)} onSelect={url?()=>setSelected(value=>value.includes(url)?value.filter(item=>item!==url):[...value,url]):undefined} onPreview={url?()=>setPreview({images,index:images.indexOf(url)}):undefined} onRetry={()=>run(()=>start(slot))} onFallbackRetry={route.fallback.configured?()=>run(()=>start(slot,"fallback")):undefined}/><small>{instructions[slot-1]}</small></div>})}</div><div className="notice">人工检查：模特一致、服装一致、手部正常、身体比例正常、服装展示完整。</div><div className="confirm-block"><button className="primary" disabled={selected.length!==3||busy||jobs.some(job=>job.status==="stale")} onClick={()=>run(()=>confirmFlow("pose",selected))}>确认三张姿势图</button></div></section>
    <section className="card settings-panel"><div className="panel-head"><h2>姿势设置</h2><small>{p.productType}模板</small></div><h3>生成模式</h3><div className="mode-grid">{[["fast","快速",modelLabel],["standard","标准",modelLabel],["quality","精细",modelLabel]].map(([key,name,model])=><button className={`mode-card ${mode===key?"active":""}`} key={key} onClick={()=>setMode(key as typeof mode)}><b>{name}</b><small>{model}</small></button>)}</div><label className="field">景别<select value={shot} onChange={e=>setShot(e.target.value)}><option>全身</option><option>上半身</option><option>下半身</option></select></label><div className="protection-grid"><label className="check-item"><input type="checkbox" checked={face} onChange={e=>setFace(e.target.checked)}/>是否露脸</label><label className="check-item"><input type="checkbox" checked={background} onChange={e=>setBackground(e.target.checked)}/>保持背景</label></div><h3>高级姿势描述</h3>{instructions.map((value,index)=><label className="field" key={index}>姿势{index+1}<textarea value={value} onChange={e=>setInstructions(current=>current.map((item,itemIndex)=>itemIndex===index?e.target.value:item))}/></label>)}<button className="secondary" onClick={()=>run(saveSettings)}>保存姿势设置</button><div className="model-card"><div className="model-row"><span>{routed?route.primary.model:health.poseProvider==="volcengine"?"Doubao Seedream 5.0":mode==="standard"?"Seedream 5.0":mode==="fast"?"FLUX.2 Klein":"FLUX.2 Pro"}</span><span className={`badge ${configured?"success":"failed"}`}>{configured?"可用":"未配置"}</span></div><small>提供商：{route.primary.providerName}</small><small>备用模型：{route.fallback.configured?`${route.fallback.providerName} / ${route.fallback.model}`:"未配置"}</small></div><div className="generate-footer"><button className="primary" disabled={busy||!sourceUrl||!configured} onClick={()=>run(()=>start())}>生成三种姿势</button></div></section>
  </div>{preview&&<ImagePreviewDialog {...preview} onClose={()=>setPreview(null)}/>}</>;
}
