"use client";
import type {Job} from "@/lib/db";

const LABELS:Record<string,string>={queued:"等待模型",generating:"正在生成",success:"生成成功",failed:"生成失败",needs_review:"需要人工审核",confirmed:"已确认",awaiting_confirmation:"等待确认",stale:"需要重新审核",interrupted:"任务已中断"};
const PHASES:Record<string,string>={queued:"等待中",uploading:"正在上传",submitting:"正在提交模型",waiting_provider:"等待模型",downloading:"正在下载",validating:"正在校验",saving:"正在保存",success:"已保存",failed:"失败",interrupted:"已中断"};
export default function ResultCard({job,label,pending,selected,onSelect,onPreview,onRetry,onFallbackRetry}:{job?:Job;label:string;pending?:boolean;selected?:boolean;onSelect?:()=>void;onPreview?:()=>void;onRetry?:()=>void;onFallbackRetry?:()=>void}){
  const url=job?.outputImages[0],status=job?.status||(pending?"queued":"idle"),labelText=job?.phase&&!['success','failed'].includes(job.phase)?PHASES[job.phase]:LABELS[status]||"等待生成";
  return <article className={selected?"result-card selected":"result-card"}><div className="result-title"><b>{label}</b><span className={`badge ${status==="failed"||status==="interrupted"?"failed":status==="confirmed"||status==="success"?"success":"wait"}`}>{labelText}</span></div>{url?<button type="button" className="image-button" onClick={onPreview} aria-label={`查看${label}大图`}><img className="result-image" src={url} alt={label}/></button>:<div className="result-placeholder"><span>{status==="failed"||status==="interrupted"?"本次生成失败\n输入素材已保留":"生成结果将在这里显示"}</span></div>}<div className="result-actions"><button className="text-button" type="button" onClick={onPreview} disabled={!url}>◉ 查看大图</button>{url&&<a className="text-button" href={url} download>↓ 下载</a>}<button className="text-button" type="button" onClick={onRetry}>↻ 重新生成</button>{(status==="failed"||status==="interrupted")&&onFallbackRetry&&<button className="text-button fallback-button" type="button" onClick={onFallbackRetry}>备用模型重试</button>}</div>{job&&<small className="job-model-line">{job.provider} · {job.model}{job.modelSlot==="fallback"?"（备用）":""}</small>}{job?.error&&<details className="error"><summary>查看错误原因</summary>{job.error}</details>}{url&&onSelect&&<label className="select-row"><input type="radio" checked={selected} onChange={onSelect}/>{selected?"已选择此结果":"选择此结果"}</label>}</article>;
}
