"use client";
import {useEffect,useState} from "react";
type Stats={outputsBytes:number;trashBytes:number;cacheBytes:number;outputPath:string};
const format=(value:number)=>value>1024*1024*1024?`${(value/1024/1024/1024).toFixed(2)} GB`:value>1024*1024?`${(value/1024/1024).toFixed(1)} MB`:`${Math.ceil(value/1024)} KB`;

export default function StorageManager(){
  const [stats,setStats]=useState<Stats|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[outputPath,setOutputPath]=useState(""),[saving,setSaving]=useState(false);
  async function refresh(){const response=await fetch("/api/storage",{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error);setStats(data);setOutputPath(data.outputPath)}
  useEffect(()=>{void refresh().catch(error=>setError(error.message))},[]);
  async function empty(){if(!confirm("确认永久清空回收站？此操作无法恢复。"))return;setError("");try{const response=await fetch("/api/storage",{method:"DELETE"}),data=await response.json();if(!response.ok)throw new Error(data.error);setStats(data);setNotice("回收站已清空")}catch(error){setError(error instanceof Error?error.message:"清空失败")}}
  async function clearCache(){setError("");const response=await fetch("/api/storage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"clear-cache"})}),data=await response.json();if(!response.ok)return setError(data.error||"清理缓存失败");setStats(data);setNotice("输出缓存已清理，项目图片未受影响")}
  async function saveLocation(){setSaving(true);setError("");setNotice("");try{const response=await fetch("/api/storage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"set-output-path",outputPath})}),data=await response.json();if(!response.ok)throw new Error(data.error||"保存位置修改失败");setStats(data);setOutputPath(data.outputPath);setNotice("新保存位置已生效；原目录中的文件没有移动或删除") }catch(error){setError(error instanceof Error?error.message:"保存位置修改失败")}finally{setSaving(false)}}
  async function copyPath(){if(!stats?.outputPath)return;await navigator.clipboard.writeText(stats.outputPath);setNotice("输出目录地址已复制")}
  return <section className="card storage-manager"><div className="panel-head"><div><h2>本地文件与回收站</h2><small>生成结果长期保存在本机输出目录</small></div><div className="actions"><button className="secondary" disabled={!stats?.outputPath} onClick={()=>void copyPath()}>复制输出目录</button><button className="secondary" disabled={!stats?.cacheBytes} onClick={()=>void clearCache()}>清理缓存</button><button className="danger" disabled={!stats?.trashBytes} onClick={empty}>清空回收站</button></div></div>{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}<div className="storage-location-editor"><label className="field">保存位置<input value={outputPath} onChange={event=>setOutputPath(event.target.value)} placeholder="例如 D:\\电商服饰工作台\\outputs"/></label><button className="primary" type="button" disabled={saving||!outputPath.trim()||outputPath===stats?.outputPath} onClick={()=>void saveLocation()}>{saving?"正在保存…":"修改保存位置"}</button><small>请输入本机完整路径。只影响后续保存，不会自动搬迁或删除原目录文件。</small></div><div className="grid"><article className="image-card"><h3>项目图片占用</h3><strong>{stats?format(stats.outputsBytes):"读取中…"}</strong></article><article className="image-card"><h3>回收站占用</h3><strong>{stats?format(stats.trashBytes):"读取中…"}</strong></article><article className="image-card"><h3>缓存占用</h3><strong>{stats?format(stats.cacheBytes):"读取中…"}</strong></article><article className="image-card"><h3>当前保存位置</h3><small className="path-text">{stats?.outputPath||"读取中…"}</small></article></div></section>
}
